<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dataprocessing" nsURI="http://www.palladiosimulator.org/pcm/dataprocessing/0.1/"
    nsPrefix="dataprocessing">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="entity" value="http://palladiosimulator.org/PalladioComponentModel/Core/Entity/5.2"/>
    <details key="identifier" value="http://sdq.ipd.uka.de/Identifier/2.1"/>
    <details key="repository_1" value="http://palladiosimulator.org/PalladioComponentModel/Repository/5.2"/>
    <details key="seff_1" value="http://palladiosimulator.org/PalladioComponentModel/SEFF/5.2"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DataSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataProcessingContainers"
        upperBound="-1" eType="#//processing/DataProcessingContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="characteristicTypeContainers"
        upperBound="-1" eType="#//characteristics/CharacteristicTypeContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="storeContainers" upperBound="-1"
        eType="#//repository/StoreContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="characteristicContainer"
        upperBound="-1" eType="#//characteristics/CharacteristicContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedCharacteristics"
        upperBound="-1" eType="#//characteristics/RelatedCharacteristics" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationSignatureDataRefinement"
        upperBound="-1" eType="#//repository/OperationSignatureDataRefinement" containment="true"/>
  </eClassifiers>
  <eSubpackages name="repository" nsURI="http://www.palladiosimulator.org/pcm/dataprocessing/repository/0.1/"
      nsPrefix="repository">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="StoreContainer" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="stores" upperBound="-1"
          eType="#//repository/Store" containment="true" eOpposite="#//repository/Store/container"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Store" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//repository/StoreContainer"
          eOpposite="#//repository/StoreContainer/stores"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationSignatureDataRefinement"
        eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterRefinements"
          lowerBound="1" upperBound="-1" eType="#//data/ParameterBasedData" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resultRefinements" lowerBound="1"
          upperBound="-1" eType="#//data/ResultBasedData" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="processing" nsURI="http://www.palladiosimulator.org/pcm/dataprocessing/processing/0.1/"
      nsPrefix="processing">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="DataProcessingContainer" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
          eType="#//processing/DataOperation" containment="true" eOpposite="#//processing/DataOperation/container"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataOperation" abstract="true" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eOperations name="determineIncomingData" ordered="false" upperBound="-1" eType="#//data/Data">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="self.oclAsSet()->selectByType(dataprocessing::data::Data)"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="determineOutgoingData" ordered="false" upperBound="-1" eType="#//data/Data">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="self.oclAsSet()->selectByType(dataprocessing::data::Data)"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//processing/DataProcessingContainer"
          eOpposite="#//processing/DataProcessingContainer/operations"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingData" ordered="false"
          upperBound="-1" eType="#//data/Data" changeable="false" volatile="true"
          transient="true" derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="derivation" value="determineIncomingData()"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingData" ordered="false"
          upperBound="-1" eType="#//data/Data" changeable="false" volatile="true"
          transient="true" derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="derivation" value="determineOutgoingData()"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreateDataOperation" eSuperTypes="#//processing/DataOperation">
      <eOperations name="determineOutgoingData" ordered="false" upperBound="-1" eType="#//data/Data">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="self.resultingData.oclAsSet()"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resultingData" lowerBound="1"
          eType="#//data/Data" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoadDataOperation" eSuperTypes="#//processing/CreateDataOperation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="store" lowerBound="1"
          eType="#//repository/Store"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoadAllDataOperation" eSuperTypes="#//processing/LoadDataOperation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="resultTypeMustBeCollection"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="resultTypeMustBeCollection" value="self.resultingData.type.oclIsKindOf(repository_1::CollectionDataType)"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PerformDataTransmissionOperation"
        eSuperTypes="#//processing/DataOperation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="outputMappingsAndOutputDataHasToMatch"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="outputMappingsAndOutputDataHasToMatch" value="outputMappings.to->asSet() = outputData->asSet()"/>
      </eAnnotations>
      <eOperations name="determineOutgoingData" ordered="false" upperBound="-1" eType="#//data/Data">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="self.outputMappings.to->asSet()"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="determineIncomingData" ordered="false" upperBound="-1" eType="#//data/Data">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="self.inputMappings.from->asSet()"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inputMappings" upperBound="-1"
          eType="#//util/DataMapping" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outputMappings" upperBound="-1"
          eType="#//util/DataMapping" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outputData" upperBound="-1"
          eType="#//data/ResultBasedData" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConsumeDataOperation" abstract="true"
        eSuperTypes="#//processing/DataOperation">
      <eOperations name="determineIncomingData" ordered="false" upperBound="-1" eType="#//data/Data">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="self.consumedData->asSet()"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="consumedData" lowerBound="1"
          eType="#//data/Data"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StoreDataOperation" eSuperTypes="#//processing/ConsumeDataOperation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="store" lowerBound="1"
          eType="#//repository/Store"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReturnDataOperation" eSuperTypes="#//processing/ConsumeDataOperation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnDestination" lowerBound="1"
          eType="#//data/ResultBasedData"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UserReadData" eSuperTypes="#//processing/ConsumeDataOperation"/>
    <eClassifiers xsi:type="ecore:EClass" name="ManyToOneDataOperation" abstract="true"
        eSuperTypes="#//processing/DataOperation">
      <eOperations name="determineIncomingData" ordered="false" upperBound="-1" eType="#//data/Data">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="self.consumedData->asSet()"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="determineOutgoingData" ordered="false" upperBound="-1" eType="#//data/Data">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="self.resultingData->asSet()"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="consumedData" lowerBound="2"
          upperBound="-1" eType="#//data/Data"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resultingData" lowerBound="1"
          eType="#//data/Data" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JoinDataOperation" eSuperTypes="#//processing/ManyToOneDataOperation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="resultMustBeCompositeOfInputs"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="resultMustBeCompositeOfInputs" value="&#xA;&#x9;&#x9;&#x9;&#x9;let resultInnerDeclarations = self.resultingData.oclAsType(repository_1::CompositeDataType).innerDeclaration_CompositeDataType in&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;resultInnerDeclarations.datatype_InnerDeclaration = self.consumedData.type"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnionDataOperation" eSuperTypes="#//processing/ManyToOneDataOperation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="inputsMustBeResultTypeOrResultEntityType"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="inputsMustBeResultTypeOrResultEntityType" value="&#xA;&#x9;&#x9;&#x9;&#x9;let entityType = self.resultingData.oclAsType(repository_1::CollectionDataType).innerType_CollectionDataType in&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;self.consumedData.type->forAll(t |&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;t = entityType or t.oclAsType(repository_1::CollectionDataType).innerType_CollectionDataType = entityType)"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TransformDataOperation" abstract="true"
        eSuperTypes="#//processing/DataOperation">
      <eOperations name="determineIncomingData" ordered="false" upperBound="-1" eType="#//data/Data">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="self.input->asSet()->union(self.parameterData)"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="determineOutgoingData" ordered="false" upperBound="-1" eType="#//data/Data">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="self.output->asSet()"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="input" lowerBound="1"
          eType="#//data/Data"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="output" lowerBound="1"
          eType="#//data/Data" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterData" upperBound="-1"
          eType="#//data/Data"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProjectionDataOperation" eSuperTypes="#//processing/TransformDataOperation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="noParameters outputIsComposedInInput"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="noParameters" value="self.parameterData->isEmpty()"/>
        <details key="outputIsComposedInInput" value="self.input.type.oclAsType(repository_1::CompositeDataType).innerDeclaration_CompositeDataType.datatype_InnerDeclaration->includes(self.output.type)"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SelectionDataOperation" eSuperTypes="#//processing/TransformDataOperation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="inputAndOutputHaveSameEntityType"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="inputAndOutputHaveSameEntityType" value="self.input.type->oclAsSet() = self.output.type->oclAsSet() or self.input.type.oclAsType(repository_1::CollectionDataType).innerType_CollectionDataType->oclAsSet() = self.output.type->oclAsSet()"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CharacteristicChangingDataOperation"
        eSuperTypes="#//processing/DataOperation">
      <eTypeParameters name="T">
        <eBounds eClassifier="#//characteristics/CharacteristicType"/>
      </eTypeParameters>
      <eOperations name="determineIncomingData" ordered="false" upperBound="-1" eType="#//data/Data">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="self.data.oclAsSet()"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="determineOutgoingData" ordered="false" upperBound="-1" eType="#//data/Data">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="self.determineIncomingData()"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="data" lowerBound="1"
          eType="#//data/Data"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
          eType="#//processing/CharacteristicChangeOperation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="characteristic" lowerBound="1"
          eType="#//characteristics/Characteristic" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CharacteristicChangeOperation">
      <eLiterals name="ADD"/>
      <eLiterals name="REMOVE"/>
      <eLiterals name="REPLACE"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="characteristics" nsURI="http://www.palladiosimulator.org/pcm/dataprocessing/characteristics/0.1/"
      nsPrefix="characteristics">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Characterizable" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="characteristicContainers"
          lowerBound="1" upperBound="-1" eType="#//characteristics/CharacteristicContainer"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="characteristics" upperBound="-1"
          eType="#//characteristics/Characteristic" changeable="false" volatile="true"
          transient="true" derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="derivation" value="self.characteristicContainers->collect(characteristics)->asOrderedSet()"/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/OCL/Collection">
          <details key="nullFree" value="false"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CharacteristicTypeContainer" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="characteristicTypes"
          upperBound="-1" eType="#//characteristics/CharacteristicType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="enumerations" upperBound="-1"
          eType="#//characteristics/Enumeration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CharacteristicType" abstract="true"
        eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity"/>
    <eClassifiers xsi:type="ecore:EClass" name="EnumCharacteristicType" eSuperTypes="#//characteristics/CharacteristicType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="multipleChoice" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="enum" lowerBound="1"
          eType="#//characteristics/Enumeration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumCharacteristicLiteral" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity"/>
    <eClassifiers xsi:type="ecore:EClass" name="CharacteristicContainer" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCharacteristics"
          upperBound="-1" eType="#//characteristics/Characteristic" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Characteristic" abstract="true" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="characteristicType" lowerBound="1"
          eType="#//characteristics/CharacteristicType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumCharacteristic" eSuperTypes="#//characteristics/Characteristic">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="valueCountMustMatchTypeRestriction literalsMustBelongToCorrectEnum"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="valueCountMustMatchTypeRestriction" value="self.literals->size() &lt; 2 or self.type.multipleChoice"/>
        <details key="literalsMustBelongToCorrectEnum" value="self.type.enum.literals->includesAll(self.literals)"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
          eType="#//characteristics/EnumCharacteristicLiteral"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//characteristics/EnumCharacteristicType"
          volatile="true" transient="true" derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="derivation" value="let type = self.characteristicType&#xA;&#x9;&#x9;&#x9;&#x9;in if type.oclIsUndefined() or not type.oclIsKindOf(EnumCharacteristicType)&#xA;&#x9;&#x9;&#x9;&#x9;then null&#xA;&#x9;&#x9;&#x9;&#x9;else type.oclAsType(EnumCharacteristicType)&#xA;&#x9;&#x9;&#x9;&#x9;endif"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
          eType="#//characteristics/EnumCharacteristicLiteral" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RelatedCharacteristics" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="characteristics" lowerBound="1"
          eType="#//characteristics/CharacteristicContainer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relatedEntity" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="data" nsURI="http://www.palladiosimulator.org/pcm/dataprocessing/data/0.1/"
      nsPrefix="data">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Data" abstract="true" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eOperations name="determineDataType" lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="null"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType"
          changeable="false" volatile="true" transient="true" derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="derivation" value="determineDataType()"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OriginalData" eSuperTypes="#//data/Data">
      <eOperations name="determineDataType" lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="originalType"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="originalType" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterBasedData" eSuperTypes="#//data/Data">
      <eOperations name="determineDataType" lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="parameter.dataType__Parameter"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/Parameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResultBasedData" eSuperTypes="#//data/Data">
      <eOperations name="determineDataType" lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="operation.returnType__OperationSignature"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/OperationSignature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DerivedData" eSuperTypes="#//data/Data">
      <eOperations name="determineDataType" lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="resultingDataType"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sources" lowerBound="1"
          upperBound="-1" eType="#//data/Data"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resultingDataType" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RefinedResultBasedData" eSuperTypes="#//data/ResultBasedData">
      <eOperations name="determineDataType" lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="refiningDataType"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="refiningDataType" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RefinedParameterBasedData" eSuperTypes="#//data/ParameterBasedData">
      <eOperations name="determineDataType" lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="refiningDataType"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="refiningDataType" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CopiedData" eSuperTypes="#//data/Data">
      <eOperations name="determineDataType" lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="source.type"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="#//data/Data"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="util" nsURI="http://www.palladiosimulator.org/pcm/dataprocessing/util/0.1/"
      nsPrefix="util">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="DataMapping" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="dataTypesMustBeTheSame"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="dataTypesMustBeTheSame" value="from.type = to.type"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1"
          eType="#//data/Data"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//data/Data"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
