<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dataprocessing" nsURI="http://www.palladiosimulator.org/pcm/dataprocessing/0.1/"
    nsPrefix="dataprocessing">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="entity" value="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity"/>
    <details key="identifier" value="../../../plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#/"/>
    <details key="repository_1" value="../../org.palladiosimulator.pcm/model/pcm.ecore#//repository"/>
    <details key="seff_1" value="../../org.palladiosimulator.pcm/model/pcm.ecore#//seff"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DataSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataProcessingContainers"
        upperBound="-1" eType="#//processing/DataProcessingContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="characteristicTypeContainers"
        upperBound="-1" eType="#//characteristics/CharacteristicTypeContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataSEFFSpecifications"
        upperBound="-1" eType="#//seff/DataSEFFSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="storeContainers" upperBound="-1"
        eType="#//repository/StoreContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="characteristicContainer"
        upperBound="-1" eType="#//characteristics/CharacteristicContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedCharacteristics"
        upperBound="-1" eType="#//characteristics/RelatedCharacteristics" containment="true"/>
  </eClassifiers>
  <eSubpackages name="repository" nsURI="http://www.palladiosimulator.org/pcm/dataprocessing/repository/0.1/"
      nsPrefix="repository">
    <eClassifiers xsi:type="ecore:EClass" name="StoreContainer" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="stores" upperBound="-1"
          eType="#//repository/Store" containment="true" eOpposite="#//repository/Store/container"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Store" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//repository/StoreContainer"
          eOpposite="#//repository/StoreContainer/stores"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="processing" nsURI="http://www.palladiosimulator.org/pcm/dataprocessing/processing/0.1/"
      nsPrefix="processing">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="DataProcessingContainer" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
          eType="#//processing/DataOperation" containment="true" eOpposite="#//processing/DataOperation/container"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataOperation" abstract="true" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//processing/DataProcessingContainer"
          eOpposite="#//processing/DataProcessingContainer/operations"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreateDataOperation" eSuperTypes="#//processing/DataOperation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resultingData" lowerBound="1"
          eType="#//data/Data" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoadDataOperation" eSuperTypes="#//processing/CreateDataOperation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="store" lowerBound="1"
          eType="#//repository/Store"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoadAllDataOperation" eSuperTypes="#//processing/LoadDataOperation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="resultTypeMustBeCollection"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="resultTypeMustBeCollection" value="self.resultingData.type.oclIsKindOf(repository_1::CollectionDataType)"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PerformDataTransmissionOperation"
        eSuperTypes="#//processing/DataOperation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="inputMappings" upperBound="-1"
          eType="#//processing/DataMapping" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outputMappings" upperBound="-1"
          eType="#//processing/DataMapping" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConsumeDataOperation" abstract="true"
        eSuperTypes="#//processing/DataOperation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="consumedData" lowerBound="1"
          eType="#//data/Data"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StoreDataOperation" eSuperTypes="#//processing/ConsumeDataOperation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="store" lowerBound="1"
          eType="#//repository/Store"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReturnDataOperation" eSuperTypes="#//processing/ConsumeDataOperation"/>
    <eClassifiers xsi:type="ecore:EClass" name="DataMapping" abstract="true" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="data" lowerBound="1"
          eType="#//data/Data"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataParameterMapping" eSuperTypes="#//processing/DataMapping">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/Parameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataResultMapping" eSuperTypes="#//processing/DataMapping">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="mappedDataMustBeInReceivedData"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="mappedDataMustBeInReceivedData" value="self.receivedData->includes(self.data)"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/OperationSignature"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="receivedData" lowerBound="1"
          eType="#//data/Data" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ManyToOneDataOperation" abstract="true"
        eSuperTypes="#//processing/DataOperation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="consumedData" lowerBound="2"
          upperBound="-1" eType="#//data/Data"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resultingData" lowerBound="1"
          eType="#//data/Data" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JoinDataOperation" eSuperTypes="#//processing/ManyToOneDataOperation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="resultMustBeCompositeOfInputs"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="resultMustBeCompositeOfInputs" value="&#xA;&#x9;&#x9;&#x9;&#x9;let resultInnerDeclarations = self.resultingData.oclAsType(repository_1::CompositeDataType).innerDeclaration_CompositeDataType in&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;resultInnerDeclarations.datatype_InnerDeclaration = self.consumedData.type"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnionDataOperation" eSuperTypes="#//processing/ManyToOneDataOperation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="inputsMustBeResultTypeOrResultEntityType"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="inputsMustBeResultTypeOrResultEntityType" value="&#xA;&#x9;&#x9;&#x9;&#x9;let entityType = self.resultingData.oclAsType(repository_1::CollectionDataType).innerType_CollectionDataType in&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;self.consumedData.type->forAll(t |&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;t = entityType or t.oclAsType(repository_1::CollectionDataType).innerType_CollectionDataType = entityType)"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TransformDataOperation" abstract="true"
        eSuperTypes="#//processing/DataOperation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" lowerBound="1"
          eType="#//data/Data"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="output" lowerBound="1"
          eType="#//data/Data" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterData" upperBound="-1"
          eType="#//data/Data"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProjectionDataOperation" eSuperTypes="#//processing/TransformDataOperation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="noParameters outputIsComposedInInput"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="noParameters" value="self.parameterData->isEmpty()"/>
        <details key="outputIsComposedInInput" value="self.inputs.type.oclAsType(repository_1::CompositeDataType).innerDeclaration_CompositeDataType.datatype_InnerDeclaration->includes(self.output.type)"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SelectionDataOperation" eSuperTypes="#//processing/TransformDataOperation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="inputAndOutputHaveSameEntityType"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="inputAndOutputHaveSameEntityType" value="self.inputs.type->oclAsSet() = self.output.type->oclAsSet() or self.inputs.type.oclAsType(repository_1::CollectionDataType).innerType_CollectionDataType->oclAsSet() = self.output.type->oclAsSet()"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CharacteristicChangingDataOperation"
        eSuperTypes="#//processing/DataOperation">
      <eTypeParameters name="T">
        <eBounds eClassifier="#//characteristics/CharacteristicType"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="data" lowerBound="1"
          eType="#//data/Data"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
          eType="#//processing/CharacteristicChangeOperation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="characteristic" lowerBound="1"
          eType="#//characteristics/Characteristic" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CharacteristicChangeOperation">
      <eLiterals name="ADD"/>
      <eLiterals name="REMOVE"/>
      <eLiterals name="REPLACE"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="characteristics" nsURI="http://www.palladiosimulator.org/pcm/dataprocessing/characteristics/0.1/"
      nsPrefix="characteristics">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Characterizable" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="characteristicContainers"
          lowerBound="1" upperBound="-1" eType="#//characteristics/CharacteristicContainer"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="characteristics" upperBound="-1"
          eType="#//characteristics/Characteristic" changeable="false" volatile="true"
          transient="true" derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="derivation" value="self.characteristicContainers->collect(characteristics)"/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/OCL/Collection">
          <details key="nullFree" value="false"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CharacteristicTypeContainer" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="characteristicTypes"
          upperBound="-1" eType="#//characteristics/CharacteristicType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="enumerations" upperBound="-1"
          eType="#//characteristics/Enumeration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CharacteristicType" abstract="true"
        eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity"/>
    <eClassifiers xsi:type="ecore:EClass" name="EnumCharacteristicType" eSuperTypes="#//characteristics/CharacteristicType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="multipleChoice" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="enum" lowerBound="1"
          eType="#//characteristics/Enumeration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumCharacteristicLiteral" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity"/>
    <eClassifiers xsi:type="ecore:EClass" name="CharacteristicContainer" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCharacteristics"
          upperBound="-1" eType="#//characteristics/Characteristic" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Characteristic" abstract="true" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="characteristicType" lowerBound="1"
          eType="#//characteristics/CharacteristicType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumCharacteristic" eSuperTypes="#//characteristics/Characteristic">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="valueCountMustMatchTypeRestriction literalsMustBelongToCorrectEnum"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="valueCountMustMatchTypeRestriction" value="self.literals->size() &lt; 2 or self.type.multipleChoice"/>
        <details key="literalsMustBelongToCorrectEnum" value="self.type.enum.literals->includesAll(self.literals)"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
          eType="#//characteristics/EnumCharacteristicLiteral"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//characteristics/EnumCharacteristicType"
          volatile="true" transient="true" derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="derivation" value="let type = self.characteristicType.oclAsType(EnumCharacteristicType)&#xA;&#x9;&#x9;&#x9;&#x9;in if type.oclIsInvalid()&#xA;&#x9;&#x9;&#x9;&#x9;then null&#xA;&#x9;&#x9;&#x9;&#x9;else type&#xA;&#x9;&#x9;&#x9;&#x9;endif"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
          eType="#//characteristics/EnumCharacteristicLiteral" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RelatedCharacteristics" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="characteristics" lowerBound="1"
          eType="#//characteristics/CharacteristicContainer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relatedEntity" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="data" nsURI="http://www.palladiosimulator.org/pcm/dataprocessing/data/0.1/"
      nsPrefix="data">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Data" abstract="true" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eOperations name="determineDataType" lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="null"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType"
          changeable="false" volatile="true" transient="true" derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="derivation" value="determineDataType()"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OriginalData" eSuperTypes="#//data/Data">
      <eOperations name="determineDataType" lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="originalType"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="originalType" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterBasedData" eSuperTypes="#//data/Data">
      <eOperations name="determineDataType" lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="parameter.dataType__Parameter"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/Parameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResultBasedData" eSuperTypes="#//data/Data">
      <eOperations name="determineDataType" lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="operation.returnType__OperationSignature"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/OperationSignature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DerivedData" eSuperTypes="#//data/Data">
      <eOperations name="determineDataType" lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="resultingDataType"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sources" lowerBound="1"
          upperBound="-1" eType="#//data/Data"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resultingDataType" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/DataType"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="seff" nsURI="http://www.palladiosimulator.org/pcm/dataprocessing/seff/0.1/"
      nsPrefix="seff">
    <eClassifiers xsi:type="ecore:EClass" name="DataSEFFSpecification" eSuperTypes="../../org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="inputData" upperBound="-1"
          eType="#//data/ParameterBasedData" containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
